### ISSUE TITLE
Create documentation pages

### ISSUE THREAD

**Issue by kylecribbs** [Recro/medulla-doc#3]
### Problem
We need a place where someone can come to read on documention, learn how they can be a contributor, etc.

### Potential Solution
GitHub Pages CI/CD with this repo? Use built in Wiki? etc

### Defining Success
Have fantastic place to read about our projects

**Comment by AndrewBabbitt97** [comment]
Think until we have a larger need, will stick with the wiki until we outgrow it. Can always migrate the markdown over when that time comes.
